### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by 1e4**
Fixed the headings to work properly - also changed SASS to SCSS as I'm pretty sure you mean SCSS and not SASS, just going to reference this SO answer as it provides a better description that I could, also your files are .scss so it makes sense to reference it as SCSS.

https://stackoverflow.com/a/27209555

### CODE REVIEW

**Comment by justinsoltesz** [comment]
Sass is correct.

http://sass-lang.com/

**Comment by 1e4** [comment]
Syntax wise MyBB2 is using SCSS not SASS

**Comment by justinsoltesz** [comment]
**Sass** is the CSS pre-processor, which is what the text you revised is referring to. Note the link in that block goes to the *Sass* website. The differentiation between `.scss` and `.sass` files is only in the syntax used. They're both still considered Sass.

**Comment by 1e4** [comment]
Fair enough, written using Sass pre processor but using sassy syntax. My bad

**Comment by WildcardSearch** [comment]
@1e4 Why close the PR? Just update the reviewed portion and we can still use this.

**Comment by 1e4** [comment]
@WildcardSearch I thought you have to close and create a new pull request for new changes?

**Comment by JordanMussi** [comment]
Just push a new commit to your `patch-1` branch and you'll be good to go! :)

**Comment by WildcardSearch** [comment]
@1e4 nope. @JordanMussi is right. Just push a commit that changes `SCSS` back to `SASS` and then we can get this reviewed and accepted 😄

**Comment by 1e4** [comment]
Sorry @WildcardSearch @JordanMussi updated that now. Will remember in future

**Pull request merged**
