### PR TITLE
Fixes #203 Search

### LINKED ISSUE #203: Search
``` php
ReflectionException in Container.php line 798
Class MyBB\Auth\Contracts\Guard does not exist
```

URL: /search

### PR DESCRIPTION
**Pull request by JN-Jones**
#203

Problem was that we assume that `id` is always an integer and add a pattern for that: https://github.com/mybb/mybb2/blob/master/app/Providers/RouteServiceProvider.php#L35
However the search id is a string so the route couldn't be found. I've simply renamed it to `token` in that route and fixed one more issue with the view.

@euantorano Probably we should rename the whole column everywhere to `token` to avoid any confusion.

### CODE REVIEW

**Comment by euantorano** [comment]
Yeah, renaming it to token everywhere would be best, can you amend this PR to do that?

**Comment by JN-Jones** [comment]
That was the plan. Need to take a look at migrations first though

**Comment by euantorano** [comment]
Nice one, cheers!

**Comment by JN-Jones** [comment]
Should be done now

**Pull request merged**
